### ISSUE TITLE
fail to parse json content

### ISSUE THREAD

**Issue by jekkay** [muhammadmuzzammil1998/jsonc#7]
```
func TestJsonParse(t *testing.T) {
	s := "{                                  " +
		"/**                                 " +
		"* environment: dev/test/online      " +
		"*/                                  " +
		"\"env\": \"dev\"                    " +
		"}                                   "
//	fmt.Println(s)
	pure := string(jsonc.ToJSON([]byte(s)))
	fmt.Println(pure)
}
```

output is 

```
{testonline"env":"dev"}
```

the correct result should be 

```
{"env":"dev"}
```

**Comment by muhammadmuzzammil1998** [comment]
Apologies for replying so late.
Will look into this as well.

**Comment by muhammadmuzzammil1998** [comment]
Yes, the issue was because the translator read the `/*` and started a comment but then here you have used two `*` as `/**` so it was looking for a slash (`/`) to end a block comment after the second `*`. I understand that this is a common way to comment and have fixed it now. Thank you for bringing this into the light. 👍
